name: Jekyll site CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker file
      run: |
        docker build -t dockerfile .
        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        unzip awscli-bundle.zip
        sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SCREATEKEY_KEY }}
        aws-region: ap-south-1
    - name: ECR Login
      run: |
       aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 292090429255.dkr.ecr.ap-south-1.amazonaws.com
       docker build -t dockerfile .
       docker tag dockerfile:latest 292090429255.dkr.ecr.ap-south-1.amazonaws.com/dockerfile:latest
       docker push 292090429255.dkr.ecr.ap-south-1.amazonaws.com/dockerfile:latest
    - name: kubectl-eks
      uses: qazz92/kubectl@1.0.3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.SCREATEKEY_KEY }}
        aws-region: ap-south-1
    - name: eksinstalltion 
      run: |
       kubectl apply -f nginx.yaml
    
   
     
