name: Jekyll site CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker file
      run: |
        docker build -t dockerfile .
        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        unzip awscli-bundle.zip
        sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
    - name: Docker ECR
      uses: appleboy/docker-ecr-action@v0.0.3
      with:
        username: ${{ secrets.AWS_ACCESSKEY }}
        password: ${{ secrets.SCREATEKEY_KEY }}
    
